[project]
name = 'contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.game-series]
path = 'contracts/game-series.clar'
clarity_version = 3
epoch = 3.1

[contracts.game-variants]
path = 'contracts/game-variants.clar'
clarity_version = 3
epoch = 3.1

[contracts.platform-manager]
path = 'contracts/platform-manager.clar'
clarity_version = 3
epoch = 3.1

[contracts.player-registry]
path = 'contracts/player-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.staking-system]
path = 'contracts/staking-system.clar'
clarity_version = 3
epoch = 3.1

[contracts.tic-tac-toe]
path = 'contracts/tic-tac-toe.clar'
clarity_version = 3
epoch = 3.1

[contracts.tournament-manager]
path = 'contracts/tournament-manager.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
